### ISSUE TITLE
strings.Split (Suggestion)

### ISSUE THREAD

**Issue by bashery** [elliotchance/ok#120]
Hi @elliotchance
I think returning one item instead of two would make more sense in cases like:
s "item;"
```len(strings.Split(s, ";")) // 2 ```
The opposite of what Golang does. is not it ??

**Comment by bashery** [comment]
```
func main() {
   s1 = ";hello;"
   s2 = ";hello;world"
   ls1 = len(strings.Split(s1, ";"))
   ls2 = len(strings.Split(s1, ";"))
   print(ls1 == ls2) // Unfortunately true 
}
```

**Comment by elliotchance** [comment]
`len(strings.Split(s, ";")) == 2` is the correct behavior in all languages I've used before. An unlimited split always returns a number of elements that is (1 + the number of deliminators) - even if the elements themselves are empty.

In your second example, I think you mean `ls2 = len(strings.Split(s2, ";"))`. However, this would still return the same result.

In the greater context of this problem, Go is really aweful with functional style programming. What I mean is that filtering the empty elements after the split isn't trivial. I haven't fully through it through, but ok should have something like:

```
items = filter(strings.Split(";hello;", ";"), func (item string) bool {
  return item != ""
})
```

**Comment by bashery** [comment]
It made sense, Thanks Eliot.
