### ISSUE TITLE
Data instead of indexs

### ISSUE THREAD

**Issue by bashery** [elliotchance/ok#36]
Hello Elliotchance!
This project looks great.

I have a small note

When we try to reade data from Array or map we want the data not index. This is mostly. Rarely, we want index.

For example:

 for X in myArray {
        print (X)
 }

I think the default should be mostly compatible.
The result: "foo" "bar" baz ".
Not: 0 1 2

And when we neede  Indexs:
  for X, _ in myArray {
         print (X)
     }

I mean the exact opposite of what golang does.

One of the things I liked most: the number. It will greatly reduce the need for Generic.
Great idea.

Finally I think it would be nice if this language to be compiled like go is not as interpreted as lua/python/js... Thank you.

**Comment by elliotchance** [comment]
Hi @bashery - thanks for your comment. At first glance this seems reasonable, at least I can't think of a reason this would be a bad idea. I'll have to think about it for a bit.

I haven't actually implemented the real idea of the language yet. The core idea is that functions are also structs and interfaces, hence the duck-typing in the description. For example:

```
// Person is a constructor that returns a type of Person (because
// there is no return type specified).
func Person(name string) {
    Name = name

    func SayHello() void {
        print("Hello", Name)
    }
}

func main() {
    // To create an instance of Person, call it's constructor.
    bob = Person("bob")

    // Interact with its public variables and methods.
    bob.Name = "Bob"
    bob.SayHello()

    // Since you can manipulate any public variable, there is
    // another way to instantiate a type that gives more control
    // over setting variables:
    jane = Person{Name: "Jane"}
    jane.SayHello()
}

// SayGoodbye takes a Person, but that's not the whole story...
func SayGoodbye(p Person) void {
    print("Hello", p.Name)
}
```

So far none of this is particularly interesting until you consider that anything can be and is an interface. Let's look at a test:

```
test "Person" {
    test "SayHello" {
        // Nothing cool here, we're just using the type directly.
        bob = Person("bob")
        assert(bob.Name == "bob")
    }
}

// Any type (function) that fulfils the methods AND variables becomes an implicit interface.
// MockPerson can contain anything, but since it contains Name and SayHello() it can be used
// as an interface for Person (and visa-versa). No more "struct vs interface" issues!
func MockPerson() {
    Name = "Imposter!"

    func SayHello() void {}
}

test "SayGoodbye" {
    imposter = MockPerson()
    SayGoodbye(imposter)
}
```

There are a few details to iron out here, but that's the idea of the language I'm working towards :)

**Comment by bashery** [comment]
Yeah.
Frankly, one of the things I liked most was Tasting. I find it more easy and sweet.

I do not have enough experience to properly judge things. I thought that modifying the source of the Goo language to implement new ideas would be easier than writing an interpreter from scratch.
I still have ideas like this. Maybe I'm wrong.

In any case Greetings to you, Mr. Eliot

**Comment by bashery** [comment]
Hi, Eliotchance. Thank you for the great work you do.
I have a small note. it's not important.
Can this Syntax be implemented?

for k, v in myrray {do somthin}
for v in myarray {...}
for k, _ in myarray {...}

I think it will be more beautiful.
 Thank you very much.

**Comment by elliotchance** [comment]
@bashery - it makes sense for the value to come first, since the value is usually required more than the index. However, it has to be consistent with all types. I do not want a different syntax based on the type because it would be confusing and make the compiler more complex. Also, I'd like to be able to add custom iterators in the future and so the value first also make more sense for this.

**Comment by bashery** [comment]
Yes the value is a logical thing. you are right.
I don't mean to implement something similar to Go. On the contrary.
Only change in Syntax order. Index and then value.
I didn't know it would have a negative effect on translation. One of the languages was built
Implement it. I don't know how complicated it is. But he was more familiar.
a: = [22,33,44]
```for k, v in a {println ("$ k: $ v")}```
0 :  22
1 :  33
2 :  44

```for v in a {println ("$ v")}```
22
33
44
```for k, _ in a {println ("$ k")}```
0
1
2
Whatever the case. It is not important. Thank you very much, Eliot.

**Comment by elliotchance** [comment]
I undertand what you're saying. However, I think that syntax is overly confusing.
